server:
    port: 9090
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/lm-4s?serverTimezone=GMT%2b8
        username: root
        password: root
mybatis-plus:
    mapper-locations: classpath:/Mapper/*mapper.xml
spring.boot.admin.client:
    enabled: true
    url: http://localhost:9090/admin
    instance:
        service-host-type: IP
    username: leapmotor
    password: 123456

--- # redis 单机配置(单机与集群只能开启一个另一个需要注释掉)
spring:
    redis:
        # 地址
        host: localhost
        # 端口，默认为6379
        port: 6379
        # 数据库索引
        database: 0
        # 密码(如没有密码请注释掉)
        # password:
        # 连接超时时间
        timeout: 10s
        # 是否开启ssl
        ssl: false

#MINIO
oss:
    name: minio
    accessKey: minioadmin
    secretKey: minioadmin
    bucketName: carimage
    endpoint: http://10.1.1.239:9000
    fileExt: png,jpg,jpeg,pdf

redisson:
    # redis key前缀
    keyPrefix: badmf
    # 线程池数量
    threads: 4
    # Netty线程池数量
    nettyThreads: 8
    # 单节点配置
    singleServerConfig:
        # 客户端名称
        clientName: ${leapmotor4s.name}
        # 最小空闲连接数
        connectionMinimumIdleSize: 8
        # 连接池大小
        connectionPoolSize: 32
        # 连接空闲超时，单位：毫秒
        idleConnectionTimeout: 10000
        # 命令等待超时，单位：毫秒
        timeout: 3000
        # 发布和订阅连接池大小
        subscriptionConnectionPoolSize: 50

